
export const supaUrl = 'https://jieefxdsdhukhjxsrotc.supabase.co'

export const anonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppZWVmeGRzZGh1a2hqeHNyb3RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwODMzMDEsImV4cCI6MjA2NDY1OTMwMX0.rc0teABDzFg-9lNBSBudWRQ60ceFX3Ps4eyXpFNinQo'